### ISSUE TITLE
یک خارج و دو ایران

### ISSUE THREAD

**Issue by Hsngh01** [peyley95/VXLAN_6to4#1]
سلام وقت بخیر میشه راهنمایی کنید که چطور این تانل را به یک خارج در دو ایران بزنم

**Comment by peyley95** [comment]
سلام و درود
شما میتونی داخل سرور خارج برای هر کدوم از سرورهای ایران یک اینترفیس 6to4 جداگونه بسازی، و یک ipv6 لوکال جدا برای هرکدوم از سرور ها داشته باشی. فقط کافیه اسمش متفاوت باشه. من داخل دستورات 6to4_OUT رو اسم پیشفرض گذاشتم. شما میتونی هر اسمی که دوست داری بذاری. برای مثال این میشه دستورات سرور خارج برای 6to4:

ip tunnel add 6to4_OUT mode sit remote <<IRAN1-IPV4>>
ip -6 addr add fd00:155::2/64 dev 6to4_OUT
ip link set 6to4_OUT mtu 1480
ip link set 6to4_OUT up

ip tunnel add 6to4_OUT mode sit remote <<IRAN2-IPV4>>
ip -6 addr add fd00:425::2/64 dev 6to4_OUT2
ip link set 6to4_OUT2 mtu 1480
ip link set 6to4_OUT2 up

بعد fd00:155::1 و fd00:425::1 رو هر کدوم رو روی یک سرور ایران ست میکنی و باهاش تانل vxlan رو اجرا میکنی.

برای vxlan هم نکته اش اینه که اسم اینترفیس (vxlan0) و vxlan id که من گذاشتم 3188 باید تغییر کنه و برای هر سرور هم یک ipv4 لوکال جداگونه تعریف بشه.

برای مثال دستورات سرور خارج به این صورت میشه:

sudo ip link add vxlan0 type vxlan id 3188 dstport 53 local fd00:155::2 remote fd00:155::1 dev ens3
sudo ip link set vxlan0 mtu 1280
sudo ip link set vxlan0 up
sudo ip addr add 192.168.23.2/30 dev vxlan0
sudo iptables -A INPUT -p udp --dport 53 -j ACCEPT
sudo ip6tables -A INPUT -p udp --dport 53 -j ACCEPT

sudo ip link add vxlan1 type vxlan id 3030 dstport 53 local fd00:425::2 remote fd00:425::1 dev ens3
sudo ip link set vxlan1 mtu 1280
sudo ip link set vxlan1 up
sudo ip addr add 192.168.25.2/30 dev vxlan1
sudo iptables -A INPUT -p udp --dport 53 -j ACCEPT
sudo ip6tables -A INPUT -p udp --dport 53 -j ACCEPT

با یه دونه ipv6 سرور هم میشه به دو یا چند تا سرور ایران تانل زد.
به اینصورت که مرحله اول (6to4) رو انجام نمیدی، در عوض vxlan رو روی دو پورت متفاوت اجرا می کنی.

**Comment by Hsngh01** [comment]
سلام خیلی ممنون

**Comment by Hsngh01** [comment]
منظورتون  با یدونه ای پی ۶ رو متوجه نشدم؟!
با v6 native خارج منظورتان هست؟
چون مرحله اول اجرا نکنم در سرورها چه ای پی برای vxlan بزنم پس

**Comment by Hsngh01** [comment]
بدون 6to4 اگه راهی باشه خیلی عالی میشه

**Comment by peyley95** [comment]
منظورم ipv6 گلوبال خود سرور هست
اگر سرور ایران و خارجی که تهیه میکنید خودشون ipv6 گلوبال داشته باشن، دیگه نیازی به 6to4 نیست و مستقیم با همون ipv6 گلوبال تانل بزنید.
