### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by Hsngh01** [peyley95/VXLAN_6to4#2]
سلام وقت بخیر ببخشید در این تانل من اگه نخوام از طریق ای پی تیبل پورت فروارد انجام بدم و از طریق دکودمودور پورت فروارد کنم این دو خط رو بازم باید بزنم؟
sudo iptables -A INPUT -p udp --dport 53 -j ACCEPT
sudo ip6tables -A INPUT -p udp --dport 53 -j ACCEPT

**Comment by peyley95** [comment]
با سلام و احترام
این دو دستور ترافیک UDP روی پورت 53 را در فایروال مجاز میکنند.
اگر فایروال روی سرور شما فعال باشه وارد کردن این دو دستور ضروریه، در غیر اینصورت نیازی نیست
